language: ruby
bundler_args: --without development testext production --deployment --jobs=4 --retry=5
cache: bundler

rvm:
  - jruby-1.7.13

matrix:
  include:
    - { rvm: jruby-1.7.13 }

env:
  - JRUBY_OPTS="--client -Xcext.enabled=false -J-Xmx900m" DISPLAY=:99.0 LOGGER_LEVEL=WARN

before_script: "./script/front-end-test.sh"
