bundler_args: --without development testext production

rvm:
  - "jruby-19mode"

matrix:
  include:
    - { rvm: jruby-19mode }

env:
  - JRUBY_OPTS="--client -Xcext.enabled=false -J-Xmx900m" DISPLAY=:99.0 LOGGER_LEVEL=WARN

before_script: "./script/front-end-test.sh"

language: ruby
cache: bundler
