development:
  adapter: postgresql
  database: <%= Settings.postgres.database %>
  encoding: unicode
  pool: 3
  timeout: 5000
  username: <%= Settings.postgres.username %>
  password: <%= Settings.postgres.password %>
  host: <%= Settings.postgres.host %>
  port: <%= Settings.postgres.port %>

production:
  adapter: postgresql
  database: <%= Settings.postgres.database %>
  encoding: unicode
  pool: <%= Settings.postgres.pool %>
  timeout: 5000
  username: <%= Settings.postgres.username %>
  password: <%= Settings.postgres.password %>
  host: <%= Settings.postgres.host %>
  port: <%= Settings.postgres.port %>

test:
  adapter: sqlite3
  encoding: utf8
  database: 'db/test.sqlite3'
  pool: <%= Settings.test_sqlite.pool %>

testext:
  adapter: postgresql
  database: <%= Settings.postgres.database %>
  encoding: unicode
  pool: 3
  timeout: 5000
  username: <%= Settings.postgres.username %>
  password: <%= Settings.postgres.password %>
  host: <%= Settings.postgres.host %>
  port: <%= Settings.postgres.port %>

# The places where these settings are filled out are settings.yml, testext.yml, and production.yml
# You should only be filling in custom values and secrets for testext.local.yml and production.local.yml
campusdb:
  adapter: <%= Settings.campusdb.adapter %>
  driver: <%=Settings.campusdb.driver %>
  url: <%=Settings.campusdb.url %>
  username: <%=Settings.campusdb.username %>
  password: <%=Settings.campusdb.password %>
  pool: <%=Settings.campusdb.pool %>
  timeout: <%=Settings.campusdb.timeout %>

