application:
  layer: "development"
logger:
  level: <%= ENV['LOGGER_LEVEL'] || DEBUG %>
  stdout: <%= ENV['LOGGER_STDOUT'] || true %>
postgres:
  database: calcentral_development
  username: calcentral_development
  password: secret
  host: localhost
  port: 5432


cache:
  expiration:
    default: <%= 35.minutes %>
    MyAcademics::Merged: <%= 1.day %>
    MyActivities: <%= 1.day %>
    MyBadges::Merged: <%= 1.day %>
    MyCampusLinksController: <%= 1.day %>
    MyClasses: <%= 1.day %>
    MyGroups: <%= 1.day %>
    MyTasks::Merged: <%= 1.day %>
    MyUpNext: <%= 1.day %>
    UserApi: <%= 1.day %>

messaging:
  enabled: false
