logger:
  level: <%= ENV['LOGGER_LEVEL'] || WARN %>
application:
  # Set if running behind Apache/Nginx + https
  protocol: "https://"
  layer: "production"
campusdb:
  adapter: jdbc
  driver: oracle.jdbc.OracleDriver
  url: jdbc:oracle:thin:@<yer_host>:<yer_port>:<yer_sid>
  username: <yer_username>
  password: <yer_password>
  pool: 5
  timeout: 5000
secret_token: some 128 char random hex string
canvas_proxy:
  export_directory: '/home/app_calcentral/calcentral/tmp/canvas'
