logger:
  level: <%= ENV['LOGGER_LEVEL'] || WARN %>
secret_token: some 128 char random hex string
application:
  # Set if running behind Apache/Nginx + https
  protocol: "https://"
  layer: "production"
  fake_proxies_enabled: false
  serve_static_assets: false
campusdb:
  adapter: jdbc
  driver: oracle.jdbc.OracleDriver
  url: jdbc:oracle:thin:@<yer_host>:<yer_port>:<yer_sid>
  username: <yer_username>
  password: <yer_password>
  pool: 95
  timeout: 5000
canvas_proxy:
  export_directory: '/home/app_calcentral/calcentral/tmp/canvas'
sakai_proxy:
