# The test environment should require minimal configuration, and is the one targeted by travis.
# Avoid creating too many dependencies (if any) on a test.local.yml
logger:
  level: <%= ENV['LOGGER_LEVEL'] || DEBUG %>
  stdout: <%= ENV['LOGGER_STDOUT'] || 'only' %>
application:
  layer: "test"
canvas_proxy:
  fake: true
google_proxy:
  fake: true
financials_proxy:
  fake: true
textbooks_proxy:
  fake: true
terms:
  # Keyed to H2 test data
  fake_now: 2013-10-11 04:20:00
sakai_proxy:
  fake: false
  # Keyed to H2 test data
  fake_now: 2013-03-11 04:20:00
cal_link_proxy:
  fake: true
cal1card_proxy:
  fake: true

# To avoid "Illegal key size" errors on systems which we can't modify (e.g., Travis),
# lower the security of the encryption algorithm.
oauth2:
  encryption: "aes-128-cbc"


app_alerts_proxy:
  fake: true
  feed_url: "http://ets-dev.berkeley.edu/calcentral-alerts/feed"

features:
  act_as: true
  bearfacts: true
  financials: true
  telebears: true
  textbooks: true
  videos: true
  podcasts: true
  research: true
  app_alerts: true
  cal1card: true
  profile_page: true

cache:
  store: "memory"
  log_level: <%= Logger::DEBUG %>
  expiration:
    default: <%= 35.minutes %>
    MyAcademics::Merged: <%= 1.day %>
    MyActivities: <%= 1.day %>
    MyBadges::Merged: <%= 1.day %>
    MyCampusLinks: <%= 1.day %>
    MyClasses::Merged: <%= 1.day %>
    Financials::MyFinancials: <%= 1.day %>
    Finaid::MyFinAid: <%= 1.day %>
    Cal1card::MyCal1card: <%= 1.day %>
    MyGroups::Merged: <%= 1.day %>
    MyTasks::Merged: <%= 1.day %>
    UpNext::MyUpNext: <%= 1.day %>
    User::Api: <%= 1.day %>
