application:
  layer: "testext"
logger:
  level: <%= ENV['LOGGER_LEVEL'] || DEBUG %>
  stdout: <%= ENV['LOGGER_STDOUT'] || 'only' %>
postgres:
  database: calcentral_test
  username: calcentral_test
  password: secret
  host: localhost
  port: 5432
campusdb:
  adapter: jdbc
  driver: oracle.jdbc.OracleDriver
  url: jdbc:oracle:thin:@<yer_host>:<yer_port>:<yer_sid>
  username: <yer_username>
  password: <yer_password>
  pool: 5
  timeout: 5000

features:
  act_as: true
  bearfacts: true

cache:
  expiration:
    default: <%= 35.minutes %>
    MyAcademics::Merged: <%= 1.day %>
    MyActivities: <%= 1.day %>
    MyBadges::Merged: <%= 1.day %>
    MyCampusLinks: <%= 1.day %>
    MyClasses: <%= 1.day %>
    MyGroups: <%= 1.day %>
    MyTasks::Merged: <%= 1.day %>
    MyUpNext: <%= 1.day %>
    UserApi: <%= 1.day %>

messaging:
  enabled: false
