application:
  layer: "testext"
logger:
  level: <%= ENV['LOGGER_LEVEL'] || DEBUG %>
  stdout: <%= ENV['LOGGER_STDOUT'] || 'only' %>
terms:
  fake_now: 2013-10-11 04:20:00
postgres:
  database: calcentral_test
  username: calcentral_test
  password: secret
  host: localhost
  port: 5432
campusdb:
  adapter: jdbc
  driver: oracle.jdbc.OracleDriver
  url: jdbc:oracle:thin:@<yer_host>:<yer_port>:<yer_sid>
  username: <yer_username>
  password: <yer_password>
  pool: 5
  timeout: 5000

features:
  act_as: true
  bearfacts: true
  financials: true
  telebears: true
  textbooks: true
  videos: true
  podcasts: true
  research: true
  app_alerts: true
  cal1card: true
  profile_page: true

cache:
  store: "memory"
  log_level: <%= Logger::DEBUG %>
  expiration:
    default: <%= 35.minutes %>
    MyAcademics::Merged: <%= 1.day %>
    MyActivities: <%= 1.day %>
    MyBadges::Merged: <%= 1.day %>
    MyCampusLinks: <%= 1.day %>
    MyClasses::Merged: <%= 1.day %>
    Financials::MyFinancials: <%= 1.day %>
    Finaid::MyFinAid: <%= 1.day %>
    Cal1card::MyCal1card: <%= 1.day %>
    MyGroups::Merged: <%= 1.day %>
    MyTasks::Merged: <%= 1.day %>
    UpNext::MyUpNext: <%= 1.day %>
    User::Api: <%= 1.day %>
