# The test environment should require minimal configuration, and is the one targeted by travis.
# Avoid creating too many dependencies (if any) on a test.local.yml
logger:
  level: <%= ENV['LOGGER_LEVEL'] || DEBUG %>
  stdout: <%= ENV['LOGGER_STDOUT'] || 'only' %>
application:
  layer: "test"
canvas_proxy:
  fake: true
google_proxy:
  fake: true
sakai_proxy:
  fake: false
  # Keyed to H2 test data
  fake_now: 2013-03-11 04:20:00
cal_link_proxy:
  fake: true

# To avoid "Illegal key size" errors on systems which we can't modify (e.g., Travis),
# lower the security of the encryption algorithm.
oauth2:
  encryption: "aes-128-cbc"

features:
  act_as: true
  bearfacts: true
